package pictodisplayer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import pictodisplayer.db.Pictodb;
import pictodisplayer.db.Category;
import pictodisplayer.db.Page;

/**
 *
 * @author Pawel Kopec <paweelkopec@gmail.com>
 */
public class CategoryPanel extends javax.swing.JPanel {

    private String categoryName;
    private Integer categoryID;
    private Category category;
    private static Index index;

    /**
     * Creates new form category
     */
    public CategoryPanel(String categoryName) {
        this.categoryName = categoryName;
        initComponents();
        try {
            category = new Category(categoryName);
            categoryDescription.setText(category.description);
        } catch (Exception e) {
            System.out.println("Error - " + e.toString());
        }
    }
    /**
     * Creates new form category
     * @param id 
     */
    public CategoryPanel(int id){
        initComponents();
        try {
            category = new Category(id);
            categoryDescription.setText(category.description);
            ImageIcon icon = new ImageIcon("C:\\PictoDisplayer\\" + category.file_name);
            this.categoryPicto.setIcon(icon);
        } catch (Exception e) {
            System.out.println("Error - " + e.toString());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        newPage = new javax.swing.JButton();
        editCategory = new javax.swing.JButton();
        usunKategorie = new javax.swing.JButton();
        projector = new javax.swing.JButton();
        categoryDescription = new javax.swing.JLabel();
        categoryPicto = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcje"));

        newPage.setText("Nowa Strona");
        newPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPageActionPerformed(evt);
            }
        });

        editCategory.setText("Edytuj  Kategorie");
        editCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCategoryActionPerformed(evt);
            }
        });

        usunKategorie.setText("Usuń Kategorie");
        usunKategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunKategorieActionPerformed(evt);
            }
        });

        projector.setText("Przeglądaj");
        projector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(newPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usunKategorie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projector)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPage)
                    .addComponent(usunKategorie)
                    .addComponent(projector)
                    .addComponent(editCategory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        categoryDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        categoryDescription.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(categoryPicto)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(categoryDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(categoryPicto)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        categoryDescription.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents
/**
     * Delete Category
     *
     * @param evt
     */
    private void usunKategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunKategorieActionPerformed
        int n = JOptionPane.showConfirmDialog(
                this,
                "Kategoria " + category.name + " zostanie usunięta",
                "An Inane Question",
                JOptionPane.YES_NO_OPTION);
        if (n == 0) {
            category.delete();
            this.setVisible(false);
            index.reLoadTree();
        }
    }//GEN-LAST:event_usunKategorieActionPerformed
    /**
     * Edit Category
     *
     * @param evt
     */
    private void editCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCategoryActionPerformed
        EditCategory eC = new EditCategory(category);
        eC.setCategPanel(this);
        eC.setVisible(true);
    }//GEN-LAST:event_editCategoryActionPerformed
    /**
     * New Page
     *
     * @param evt
     */
    private void newPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPageActionPerformed
        NewPage nP = new NewPage(category.id);
        nP.setIndex(index);
        nP.setVisible(true);
    }//GEN-LAST:event_newPageActionPerformed

    private void projectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectorActionPerformed
        Projector projector = new Projector(this.category.id);
        projector.setVisible(true);
    }//GEN-LAST:event_projectorActionPerformed
    /**
     * Set Index
     *
     * @param i
     */
    public static void setIndex(Index i) {
        index = i;
    }

    /**
     * Refresh
     */
    public void refresh() {
        index.reLoadTree();
        categoryDescription.setText(category.description);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryDescription;
    private javax.swing.JLabel categoryPicto;
    private javax.swing.JButton editCategory;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JButton newPage;
    private javax.swing.JButton projector;
    private javax.swing.JButton usunKategorie;
    // End of variables declaration//GEN-END:variables
}
