/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pictodisplayer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import pictodisplayer.db.Pictodb;
import pictodisplayer.db.Category;

/**
 *
 * @author Pawel Kopec <paweelkopec@gmail.com>
 */
public class CategoryPanel extends javax.swing.JPanel {

    private String categoryName;
    private Integer categoryID;
    private Category category;
    private static Index index;
    
    /**
     * Creates new form category
     */
    public CategoryPanel(String categoryName) {
        this.categoryName = categoryName;
        initComponents();
        
        try {
            category = new Category();
            category.loadFromName(categoryName);
            categoryDescription.setText(category.description);    

        } catch (Exception e) {
            
            System.out.println("Error - " + e.toString());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        newPage = new javax.swing.JButton();
        editCategory = new javax.swing.JButton();
        usunKategorie = new javax.swing.JButton();
        categoryDescription = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcje"));

        newPage.setText("Nowa Strona");
        newPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPageActionPerformed(evt);
            }
        });

        editCategory.setText("Edytuj  Kategorie");
        editCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCategoryActionPerformed(evt);
            }
        });

        usunKategorie.setText("Usuń Kategorie");
        usunKategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunKategorieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(newPage)
                .addGap(18, 18, 18)
                .addComponent(editCategory)
                .addGap(18, 18, 18)
                .addComponent(usunKategorie)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPage)
                    .addComponent(editCategory)
                    .addComponent(usunKategorie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        categoryDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        categoryDescription.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(categoryDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(categoryDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        categoryDescription.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void usunKategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunKategorieActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(
                this,
                "Kategoria "+category.name+" zostanie usunięta",
                "An Inane Question",
                JOptionPane.YES_NO_OPTION);

        if(n==0){
            category.delete();
            this.setVisible(false);
            index.reLoadTree();
        }


    }//GEN-LAST:event_usunKategorieActionPerformed

    private void editCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCategoryActionPerformed
        // TODO add your handling code here:
        EditCategory eC = new EditCategory(category);
        eC.setCategPanel(this);
        eC.setVisible(true);
    }//GEN-LAST:event_editCategoryActionPerformed

    private void newPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPageActionPerformed
        // TODO add your handling code here:
        NewPage nP = new NewPage(category.id);
        nP.setIndex(index);
        nP.setVisible(true);
    }//GEN-LAST:event_newPageActionPerformed
    public static void setIndex(Index i){
        index = i;
    }
    
    public void refresh(){
        index.reLoadTree();
        categoryDescription.setText(category.description);  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryDescription;
    private javax.swing.JButton editCategory;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JButton newPage;
    private javax.swing.JButton usunKategorie;
    // End of variables declaration//GEN-END:variables
}
