package pictodisplayer;

import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * Image panel content
 */
public class ImagePanel extends javax.swing.JPanel {

    /**
     * Creates new form ImagePane
     */
    public ImagePanel() {
        setLayout(new WrapLayout());
        setBackground(Color.white);
    }

    @Override
    public Dimension getPreferredSize() {
        return getComponentCount() == 0 ? new Dimension(200, 200) : super.getPreferredSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
